SOURCE_DATA = "E:\Kinga\Studies-mgr\Semestr 3\Praca dyplomowa\Dataset\k_d_t"
SOURCE_DATA2 = "E:\Kinga\Studies-mgr\Semestr 3\Praca dyplomowa\Dataset\k_d"
DATA_WITH_HEADERS = "E:\Kinga\Studies-mgr\Semestr 3\Praca dyplomowa\Dataset\k_h"
DATA_WITH_HEADERS2 = "E:\Kinga\Studies-mgr\Semestr 3\Praca dyplomowa\Dataset\k_d_h"
DESTINATION_FOLDER = "E:\Kinga\Studies-mgr\Semestr 3\Praca dyplomowa\Dataset"
CITY = "WARSZAWA-FILTRY"
FILENAME = "\warsaw-filtry2.csv"
TRAIN_SIZE = 3500
N_DAYS = 3
N_FEATURES = 9
N_OBS = N_DAYS * N_FEATURES
